### ISSUE TITLE
login issue 

### ISSUE THREAD

**Issue by Harshsuakhe** [Arbind15/myhaircare#2]
sir login issue lisecence number and password

**Comment by Arbind15** [comment]
License number is equivalent to Django username, create default user with command provided by Django and use it.

**Comment by Harshsuakhe** [comment]
sir after creating it and trying to login but getting server error can you help sir

**Comment by Harshsuakhe** [comment]
![Screenshot 2024-02-24 215233](https://github.com/Arbind15/myhaircare/assets/159647104/dc905a7d-7f50-45c4-8efc-885e33375078)
this what i am getting sir

**Comment by Arbind15** [comment]
Share the server logs.

**Comment by Harshsuakhe** [comment]
February 24, 2024 - 21:50:58
Django version 4.0.2, using settings 'MyHair.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[24/Feb/2024 21:51:01] "GET / HTTP/1.1" 200 2503
[24/Feb/2024 21:51:06] "GET /login/ HTTP/1.1" 200 11707
[24/Feb/2024 21:51:21] "POST /login/ HTTP/1.1" 200 12280
[24/Feb/2024 21:51:24] "POST /login/ HTTP/1.1" 302 0
[24/Feb/2024 21:51:24] "GET /home/ HTTP/1.1" 500 145

**Comment by Arbind15** [comment]
Will check it. Thank you.

**Comment by Harshsuakhe** [comment]
ok sir 
only survey and admin page is working even dr details cannot bee added please check that also sir
